#Define o nome da aplicação Spring:
spring.application.name=course

#Isso define qual perfil da aplicação está ativo. 
#Então o Spring vai carregar: application-test.properties
#Isso permite ter configurações diferentes para cada ambiente.
#Perfil = ambiente de execução (dev, test, prod):
spring.profiles.active=test
spring.jpa.open-in-view=true
